### ISSUE TITLE
No search results returned

### ISSUE THREAD

**Issue by ljo123** [evan-buss/openbooks#120]
Running the latest version and added both --name "randomuser123" and --useragent "HexChat 2.9.1" to my docker-compose. Docker logs show that client is connected and "CONNECT Message Received". Then I enter a search and see "SEARCH Message Received" but the results are blank. I tried a few popular books so I'd expect to see some results at least. My compose...

```
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    volumes:
      - /path/to/books:/books
    ports:
      - 8585:80
    command: --persist --no-browser-downloads --name "randomuser123" --useragent "HexChat 2.9.1"
    restart: unless-stopped
```

Any ideas?

**Comment by evan-buss** [comment]
Do you see a "Search Accepted Into Queue" notification in the browser? If not, it's possible you're temporarily banned in the IRC channel. If you enable logs with the `--log` flag it will write all the IRC messages sent to your client.

**Comment by daedric7** [comment]
Can confirm. I really don't see any error in the logs:

```
OpenBooks  | 2023/01/10 01:39:13 CLIENT (daedric): New client created.
OpenBooks  | 2023/01/10 01:39:13 CLIENT (daedric): CONNECT Message Received
OpenBooks  | 2023/01/10 01:39:23 CLIENT (daedric): SEARCH Message Received
```
And that's it.

**Comment by smee42** [comment]
I'm also seeing exactly the same thing since updating to the latest version.  Logs have the same as what daedric7 is seeing - Docker log shows the search message received, but the detailed irc log has nothing relating to the search in it.

**Comment by baristasake** [comment]
It seems to work for me without passing the useragent command.

**Comment by hackmonker** [comment]
can confirm here too. no results are shown

**Comment by daedric7** [comment]
I can confirm the issue is somewhere with Openbooks. 

I joined the IRC and searches work, Search is answering via Notices, and sending search results via DCC.

**Comment by ljo123** [comment]
> It seems to work for me without passing the useragent command.

After you posted that I tried again without the useragent string but got the same result.

**Comment by xenolithis** [comment]
not seeing any results or the "Search Accepted into Queue" in browser with following conf
```
---
services:
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    volumes:
      - /srv/media/downloads/:/books
    ports:
      - 12443:80
    restart: unless-stopped
    command: --persist  --name lookin4books1337 --log --no-browser-downloads
```
