### ISSUE TITLE
Not getting any results back (no server connection)

### ISSUE THREAD

**Issue by MyShlongIsLongAT** [evan-buss/openbooks#132]
I'm using following compose file (it's part of a bigger one, so version and service is missing):
```
openbooks:
    image: evanbuss/openbooks:latest
    restart: unless-stopped
    ports:
      - "8787:80"
    volumes:
      - "/mnt/raid1/openbooks:/books"
    command: --persist -n aufoilolfbolf --log
```
after composing up i am able to open the webgui.
![image](https://user-images.githubusercontent.com/72039636/216841679-589dd643-ce82-480a-808c-a42ffdb0588c.png)

But the WebGUI shows, that I'm not able to connect to the IRC-Server...

docker logs show:
![image](https://user-images.githubusercontent.com/72039636/216841336-6de94030-86a1-4744-8558-01fa00284247.png)

openbooks logs are not beeing generated, due to the not existing connection i guess...
![image](https://user-images.githubusercontent.com/72039636/216841565-d386fd3b-8c89-4aeb-93c2-d852843a0c7b.png)

After setting `--tls=false` in the compose file i got a connection to the server, but my container is not getting any response from the server.

After reading some issues i recognized, that I am not the only person getting no server response / connection.

Hope u guys can help me :)
