### ISSUE TITLE
Running Docker image missing --name flag

### ISSUE THREAD

**Issue by GeorgelPreput** [evan-buss/openbooks#133]
When deploying and running the Docker image, the application fails and complains about not being given the --name parameter, as in the screenshot below. The Dockerfile indeed runs the application without that parameter:

`ENTRYPOINT ["./openbooks", "server", "--dir", "/books", "--port", "80"]`

In certain scenarios, such as cloud deployment directly from Docker Hub, it becomes rather convoluted to change this. Two suggestions for mitigation would be:

In the main app:
- Either also read the name from the environment variables and only throw an error if the env var has also not been set
- Or provide a default for the --name flag (such as "openbooks", or even generate one on the fly)

Thanks!

![image](https://user-images.githubusercontent.com/94863939/220445057-8108f75e-d409-4e16-9ca3-48f2a1cb9067.png)

**Comment by Kr1sDarnok** [comment]
Same issue here, never happened before though

**Comment by alfdav** [comment]
add the flag `--name` and invent any name and it will connect. 

However, as of today I can't figure out what's blocking the connection and preventing the search function to work. I believe it has to do with the TLS or something of sorts.

**Comment by frollard** [comment]
Same - using unraid can't push a post-argument, only port path variable label or device...none of which are picked up by the container.

**Comment by Unrepentant-Atheist** [comment]
I got the same problem, `docker run -p 8080:80 evanbuss/openbooks --name randomcoolnickname` doesn't help.

**Comment by canedje** [comment]
same here

**Comment by canedje** [comment]
I did find the answer for uraid:
I did find the answer:
You need to add:
![image](https://github.com/evan-buss/openbooks/assets/23150947/05540b8d-0bdd-4e4a-9aa4-c1931406a944)
At Post arguments in advanced mode

**Comment by etuck** [comment]
And if anyone is using a Docker Compose file the fix is to add a "command" attribute.

```
version: "3"
services:
  openbooks:
    container_name: openbooks
    image: evanbuss/openbooks:latest
    environment:
      TZ: America/New_York
    ports:
      - 8071:80
    volumes:
      - /path/to/openbooks:/books    
    command: --name CoolName --persist
```
