### ISSUE TITLE
Unable to get working on synology

### ISSUE THREAD

**Issue by ThinkSalat** [evan-buss/openbooks#142]
When I go to localhost:8005, it says site cannot be reached. The logs say its' working and listening on port 80. Here's my docker compose. I've tried several different combinations of ports and nothing works.

```
version: "3.3"
services:
  openbooks:
    container_name: OpenBooks
    image: evanbuss/openbooks:latest
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - "/volume1/data/media/books/openbooks:/books"
      - "/volume1/docker/openbooks:/openbooks"
    command: --persist --name thinksalat --searchbot search --server irc.irchighway.net:6697 --tls true --useragent "OpenBooks v4.5.0"
    environment:
      - BASE_PATH=/openbooks/
```
