### ISSUE TITLE
TLS not working

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [evan-buss/openbooks#145]
I got this docker-compose running:

```
---
version: '3.3'
services:
    openbooks:
        image: evanbuss/openbooks
        container_name: openbooks
        #command: --name dontwannagive --persist
        command: --name dontwannagive --persist --tls=false -s irc.irchighway.net:6660
        ports:
            - 8180:80
        volumes:
            - /home/xxx/docker-data/openbooks:/books
        environment:
            - NODE_ENV=production
        labels:
            - deunhealth.restart.on.unhealthy=true
        restart: unless-stopped
networks:
  default:
    name: dockernet
    external: true
```

Notice `command: --name dontwannagive --persist --tls=false -s irc.irchighway.net:6660` --> `--tls=false` , if I turn it to true, then it can't connect to the IRC. Kinda want to use encryption...
