### ISSUE TITLE
I/O Timeout

### ISSUE THREAD

**Issue by stevesec** [evan-buss/openbooks#160]
## Issue
Getting a DNS timeout when looking up irc.irchighway.net on my host IP.

```
dial tcp: lookup irc.irchighway.net on HOST:53: read udp 172.17.0.2:45990->HOST:53: i/o timeout
```

1. If I remove "network_mode" in the Docker compose file, it will state that the server is misbhaving
2. Running in Docker on an Ubuntu Server
3. Running Openbooks behind an NGINX reverse proxy

**Comment by stevesec** [comment]
Can be closed, need to set the DNS directive in the docker-compose file:

```
version: "3"
services:
  openbooks:
    dns:
    - '1.1.1.1'
    - '1.0.0.1'
    container_name: openbooks
    image: evanbuss/openbooks:latest
    environment:
      TZ: America/New_York
    ports:
      - "127.0.0.1:9000:80"
    volumes:
      - /dir:/books
    command: -n Username--tls=false --no-browser-downloads --persist -s irc.irchighway.net:9999 --log --searchbot searchook
```
