### ISSUE TITLE
Don't `mkdir books`

### ISSUE THREAD

**Issue by typkrft** [evan-buss/openbooks#60]
Is it possible not to run `mkdir books`? I could be completely off base, but generally when I mount a volume to a path I'm expecting the data to be in that path. Making another `books` directory in `/books` seems redundant. This is not a huge deal though, just a thought. 

My Compose:

```YAML
version: "3.9"

volumes:
  books:
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_IP},nolock,soft,rw"
      device: ":${NAS_MEDIA_PATH}/Literature/Books"

services:
  openbooks:
    container_name: openBooks
    image: evanbuss/openbooks:latest
    environment:
      - BASE_PATH=/openbooks/
    volumes:
      - 'books:/books'
    ports:
      - '17012:80'
    restart: unless-stopped
    command: --persist
```
