### ISSUE TITLE
[FR] Ability to Download to servers HDD instead of devices

### ISSUE THREAD

**Issue by mim212** [evan-buss/openbooks#69]
It would be an amazing addition if instead of downloading the  result to the device you are viewing the webpage on (a phone for instance), if there was the ability to save it to the attached volume ie the 'books' directory which could be elsewhere on a server. 

The Docker compose example shows the ability to map a volume to the container as 'books' for example, but as far as I can see it remains unused? 

```
services:
    openbooks:
        ports:
            - '8080:80'
        volumes:
            - 'booksVolume:/books'
        restart: unless-stopped
        container_name: OpenBooks
        command: --persist
        environment:
          - BASE_PATH=/openbooks/
        image: evanbuss/openbooks:latest

volumes:
    booksVolume:
```
