### ISSUE TITLE
Persist books with user (not root) permissions

### ISSUE THREAD

**Issue by vik-s** [evan-buss/openbooks#92]
Hey, I'm running the latest docker install of Openbooks. I absolutely love it, thanks for your work. One issue I run into is, when I download books, they are stored in the persist directory with root permissions. This stops Calibre from running Auto-import till I change the permission of the downloaded books, into my user permissions. I do not run the docker container as root, but instead as my specified docker user.

Is there any way  I can define the owner / permissions of the books being persisted?

Thanks!

**Comment by sbelongie** [comment]
would like to know a way to fix this issue as well.

**Comment by robflate** [comment]
anyone found a solution to this?

**Comment by CyBuzz** [comment]
I just wrote a cron job to change the permissions of files in the download folder and it runs every 5 minutes. The books get picked up by Calibre once the permissions change.

**Comment by knipster** [comment]
Also having this issue....

**Comment by 4very** [comment]
You can specify the UID and GID of a container via compose. Cheers!

```
  openbooks:
    restart: unless-stopped
    container_name: openbooks
    command: --name my_irc_name --persist --port 80 --no-browser-downloads -d /books
    image: evanbuss/openbooks:latest
    user: "${PUID}:${PGID}"
```

**Comment by mikaeltarquin** [comment]
> You can specify the UID and GID of a container via compose. Cheers!
> 
> ```
>   openbooks:
>     restart: unless-stopped
>     container_name: openbooks
>     command: --name my_irc_name --persist --port 80 --no-browser-downloads -d /books
>     image: evanbuss/openbooks:latest
>     user: "1002:1002"
> ```

I found this post while trying to figure out this exact issue (openbooks to calibre auto-add from folder). I added the user line exactly, but files are still coming in with read only permissions for "group" and "other" (-rw-r--r--), as far as my unraid server can tell. Here is my full docker compose file, not sure what the issue is:
```
version: '3.3'
services:
    openbooks:
        container_name: OpenBooks
        image: evanbuss/openbooks:latest
        ports:
            - "8585:80"
        volumes:
            - '/mnt/user/data/media/eBooks/to_import:/books'
        command: --name my_irc_name --persist --no-browser-downloads
        restart: unless-stopped
        environment:
          - BASE_PATH=/openbooks/
        user: "1002:1002"
volumes:
    booksVolume:
```
